/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "شريط جانبي",
        _layout_FIRST_label: "الأول",
        _layout_SECOND_label: "ثانية",
        _action_toggleSidebar_label: "تبديل الشريط الجانبي",
        _action_openSidebar_label: "فتح شريط جانبي",
        widgetProperties: "خصائص عنصر واجهة الاستخدام",
        widgetFunctions: "وظائف عنصر واجهة المستخدم",
        widgetName: "اسم عنصر واجهة المستخدم",
        widgetProps: "خصائص عنصر واجهة المستخدم:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
