/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Странична лента",
        _layout_FIRST_label: "Първи",
        _layout_SECOND_label: "Секунда",
        _action_toggleSidebar_label: "Превключване на страничната лента",
        _action_openSidebar_label: "Отваряне на страничната лента",
        widgetProperties: "Свойства на изпълнимия модул",
        widgetFunctions: "Функции на изпълнимия модул",
        widgetName: "име на изпълнимия модул:",
        widgetProps: "свойства на изпълнимия модул:",
        noLayoutComponent: "Няма макетен компонент!",
        unknownError: "неизвестна грешка",
        unserializableError: "несериозна грешка",
        online101: "Онлайн 10.1."
      })
    }
  }
})
