/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Bočna traka",
        _layout_FIRST_label: "Prvo",
        _layout_SECOND_label: "Drugo",
        _action_toggleSidebar_label: "Uključi/isključi bočnu traku",
        _action_openSidebar_label: "Otvori bočnu traku",
        widgetProperties: "Vlasništva widgeta",
        widgetFunctions: "Funkcije widgeta",
        widgetName: "naziv widgeta:",
        widgetProps: "vlasništva widgeta:"
      })
    }
  }
})
