/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Postranní lišta",
        _layout_FIRST_label: "První",
        _layout_SECOND_label: "Druhá",
        _action_toggleSidebar_label: "Přepnout postranní lištu",
        _action_openSidebar_label: "Otevřít postranní lištu",
        widgetProperties: "Vlastnosti widgetu",
        widgetFunctions: "Funkce widgetu",
        widgetName: "Název widgetu:",
        widgetProps: "Vlastnosti widgetu:"
      })
    }
  }
})
