/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Πλαϊνή γραμμή",
        _layout_FIRST_label: "Πρώτο",
        _layout_SECOND_label: "Δευτερολέπτων",
        _action_toggleSidebar_label: "Εναλλαγή πλαϊνής μπάρας",
        _action_openSidebar_label: "Ανοιχτή πλαϊνή μπάρα",
        widgetProperties: "Ιδιότητες του widget",
        widgetFunctions: "Λειτουργίες του widget",
        widgetName: "όνομα του widget:",
        widgetProps: "ιδιότητες του widget:",
        noLayoutComponent: "Δεν υπάρχει διάταξη!",
        unknownError: "άγνωστο σφάλμα",
        unserializableError: "σφάλμα μη ανιχνεύσιμο",
        online101: "Σε σύνδεση 10.1."
      })
    }
  }
})
