/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Külgriba",
        _layout_FIRST_label: "Esimene",
        _layout_SECOND_label: "Sekund",
        _action_toggleSidebar_label: "Lülita külgriba",
        _action_openSidebar_label: "Ava külgriba",
        widgetProperties: "Vidina omadused",
        widgetFunctions: "Vidina funktsioonid",
        widgetName: "vidina nimi:",
        widgetProps: "vidina omadused:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
