/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Sivupalkki",
        _layout_FIRST_label: "Ensimmäinen",
        _layout_SECOND_label: "Sekunti",
        _action_toggleSidebar_label: "Vaihda sivupalkkia",
        _action_openSidebar_label: "Avaa sivupalkki",
        widgetProperties: "Pienoisohjelman ominaisuudet",
        widgetFunctions: "Pienoisohjelman toiminnot",
        widgetName: "pienoisohjelman nimi:",
        widgetProps: "pienoisohjelman ominaisuudet:",
        noLayoutComponent: "Ei layout-komponenttia!",
        unknownError: "tuntematon virhe",
        unserializableError: "epätavallinen virhe",
        online101: "Online 10.1."
      })
    }
  }
})
