/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Barre latérale",
        _layout_FIRST_label: "Premier",
        _layout_SECOND_label: "Seconde",
        _action_toggleSidebar_label: "Activer/désactiver la barre latérale",
        _action_openSidebar_label: "Ouvrir la barre latérale",
        widgetProperties: "Propriétés du widget",
        widgetFunctions: "Fonctions du widget",
        widgetName: "Nom du widget :",
        widgetProps: "Propriétés du widget :",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
