/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "סרגל צד",
        _layout_FIRST_label: "ראשון",
        _layout_SECOND_label: "שנייה",
        _action_toggleSidebar_label: "החלף מצב סרגל צד",
        _action_openSidebar_label: "פתח סרגל צד",
        widgetProperties: "מאפייני ווידג'ט",
        widgetFunctions: "פונקציות ווידג'ט",
        widgetName: "שם ווידג'ט:",
        widgetProps: "מאפייני ווידג'ט:",
        noLayoutComponent: "אין רכיב פריסה!",
        unknownError: "טעות לא ידועה",
        unserializableError: "טעות בלתי אפשרית",
        online101: "באינטרנט 10.1."
      })
    }
  }
})
