/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Oldalsáv",
        _layout_FIRST_label: "Első",
        _layout_SECOND_label: "Második",
        _action_toggleSidebar_label: "Oldalsáv ki-/bekapcsolása",
        _action_openSidebar_label: "Oldalsáv megnyitása",
        widgetProperties: "Widget tulajdonságai",
        widgetFunctions: "Widget függvényei",
        widgetName: "widget neve:",
        widgetProps: "widget tulajdonságai:",
        noLayoutComponent: "Nincs elrendezési elem!",
        unknownError: "ismeretlen hiba",
        unserializableError: "nem sorozható hiba",
        online101: "Online 10.1."
      })
    }
  }
})
