/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Bilah samping",
        _layout_FIRST_label: "Pertama",
        _layout_SECOND_label: "Kedua",
        _action_toggleSidebar_label: "Alihkan bilah samping",
        _action_openSidebar_label: "Buka bilah samping",
        widgetProperties: "Properti widget",
        widgetFunctions: "Fungsi widget",
        widgetName: "nama widget:",
        widgetProps: "properti widget:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
