/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Barra laterale",
        _layout_FIRST_label: "Prima",
        _layout_SECOND_label: "Secondo",
        _action_toggleSidebar_label: "Attiva/disattiva barra laterale",
        _action_openSidebar_label: "Apri barra laterale",
        widgetProperties: "Proprietà del widget",
        widgetFunctions: "Funzioni del widget",
        widgetName: "nome del widget:",
        widgetProps: "proprietà del widget:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
