/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "サイドバー",
        _layout_FIRST_label: "1 番目",
        _layout_SECOND_label: "2 番目",
        _action_toggleSidebar_label: "サイドバーの切り替え",
        _action_openSidebar_label: "サイドバーを開く",
        widgetProperties: "ウィジェットのプロパティ",
        widgetFunctions: "ウィジェット関数",
        widgetName: "ウィジェット名:",
        widgetProps: "ウィジェットのプロパティ:",
        noLayoutComponent: "レイアウトコンポーネントなし!",
        unknownError: "未知のエラー",
        unserializableError: "unserializable エラー",
        online101: "オンライン 10.1."
      })
    }
  }
})
