/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "사이드바",
        _layout_FIRST_label: "첫번째 요소",
        _layout_SECOND_label: "두번째 요소",
        _action_toggleSidebar_label: "사이드바 전환",
        _action_openSidebar_label: "사이드바 열기",
        widgetProperties: "위젯 등록정보",
        widgetFunctions: "위젯 기능",
        widgetName: "위젯 이름:",
        widgetProps: "위젯 속성:",
        noLayoutComponent: "레이아웃 구성 요소 없음!",
        unknownError: "알 수없는 오류",
        unserializableError: "unserializable 오류",
        online101: "온라인 10.1."
      })
    }
  }
})
