/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Šoninė juosta",
        _layout_FIRST_label: "Pirmas",
        _layout_SECOND_label: "Antras",
        _action_toggleSidebar_label: "Perjungti šoninę juostą",
        _action_openSidebar_label: "Atidaryti šoninę juostą",
        widgetProperties: "Valdiklio savybės",
        widgetFunctions: "Valdiklio funkcijos",
        widgetName: "valdiklio pavadinimas:",
        widgetProps: "valdiklio savybės:"
      })
    }
  }
})
