/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Sānjosla",
        _layout_FIRST_label: "Pirmais",
        _layout_SECOND_label: "Otrais",
        _action_toggleSidebar_label: "Pārslēgt sānjoslu",
        _action_openSidebar_label: "Atvērt sānjoslu",
        widgetProperties: "Logrīka īpašības",
        widgetFunctions: "Logrīka funkcijas",
        widgetName: "logrīka nosaukums:",
        widgetProps: "logrīka īpašības:"
      })
    }
  }
})
