/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Zijbalk",
        _layout_FIRST_label: "Eerste",
        _layout_SECOND_label: "Tweede",
        _action_toggleSidebar_label: "Zijbalk in-/uitschakelen",
        _action_openSidebar_label: "Zijbalk openen",
        widgetProperties: "Widget Eigenschappen",
        widgetFunctions: "Widgetfuncties",
        widgetName: "widgetnaam:",
        widgetProps: "widgeteigenschappen:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
