/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Sidefelt",
        _layout_FIRST_label: "Første",
        _layout_SECOND_label: "Sekund",
        _action_toggleSidebar_label: "Aktiver/deaktiver sidestolpe",
        _action_openSidebar_label: "Åpne sidestolpe",
        widgetProperties: "Miniprogramegenskaper",
        widgetFunctions: "Miniprogramfunksjoner",
        widgetName: "Navn på miniprogram:",
        widgetProps: "Miniprogramegenskaper:",
        noLayoutComponent: "Ingen layout komponent!",
        unknownError: "ukjent feil",
        unserializableError: "uiserbar feil",
        online101: "Online 10.1."
      })
    }
  }
})
