/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Pasek boczny",
        _layout_FIRST_label: "Pierwszy",
        _layout_SECOND_label: "Sekunda",
        _action_toggleSidebar_label: "Przełącz pasek boczny",
        _action_openSidebar_label: "Otwórz pasek boczny",
        widgetProperties: "Właściwości widżetów",
        widgetFunctions: "Funkcje widżetu",
        widgetName: "nazwa widżetu:",
        widgetProps: "właściwości widżetu:"
      })
    }
  }
})
