/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Barra lateral",
        _layout_FIRST_label: "Primeiro",
        _layout_SECOND_label: "Segundo",
        _action_toggleSidebar_label: "Ativar/Desativar barra lateral",
        _action_openSidebar_label: "Abrir barra lateral",
        widgetProperties: "Propriedades de widget",
        widgetFunctions: "Funções dos widgets",
        widgetName: "nome do widget:",
        widgetProps: "propriedades do widget:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
