/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Bară laterală",
        _layout_FIRST_label: "La început",
        _layout_SECOND_label: "Secundă",
        _action_toggleSidebar_label: "Comutare bară laterală",
        _action_openSidebar_label: "Deschidere bară laterală",
        widgetProperties: "Proprietăți widget",
        widgetFunctions: "Funcții widget",
        widgetName: "Nume widget:",
        widgetProps: "Proprietăți widget:"
      })
    }
  }
})
