/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Боковая панель",
        _layout_FIRST_label: "Первый",
        _layout_SECOND_label: "Секунды",
        _action_toggleSidebar_label: "Переключить боковую панель",
        _action_openSidebar_label: "Открыть боковую панель",
        widgetProperties: "Свойства виджета",
        widgetFunctions: "Функции виджета",
        widgetName: "имя виджета:",
        widgetProps: "свойства виджета:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
