/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Bočný panel",
        _layout_FIRST_label: "Prvá",
        _layout_SECOND_label: "Druhá",
        _action_toggleSidebar_label: "Prepínanie bočného panela",
        _action_openSidebar_label: "Otvoriť bočný panel",
        widgetProperties: "Vlastnosti widgetu",
        widgetFunctions: "Funkcie widgetu",
        widgetName: "názov widgetu:",
        widgetProps: "vlastnosti widgetu:",
        noLayoutComponent: "Žiadny komponent!",
        unknownError: "neznáma chyba",
        unserializableError: "neserializovateľná chyba",
        online101: "Online 10.1."
      })
    }
  }
})
