/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Stranska vrstica",
        _layout_FIRST_label: "Prvi",
        _layout_SECOND_label: "Sekunda",
        _action_toggleSidebar_label: "Preklopi stransko vrstico",
        _action_openSidebar_label: "Odpri stransko vrstico",
        widgetProperties: "Lastnosti pripomočka",
        widgetFunctions: "Funkcije pripomočka",
        widgetName: "ime pripomočka:",
        widgetProps: "lastnosti pripomočka:"
      })
    }
  }
})
