/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Bočna traka",
        _layout_FIRST_label: "Prvi",
        _layout_SECOND_label: "Druga",
        _action_toggleSidebar_label: "Uključi/isključi bočnu traku",
        _action_openSidebar_label: "Otvori bočnu traku",
        widgetProperties: "Svojstva vidžeta",
        widgetFunctions: "Funkcije vidžeta",
        widgetName: "naziv vidžeta:",
        widgetProps: "svojstva vidžeta:"
      })
    }
  }
})
