/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Sidofält",
        _layout_FIRST_label: "Första",
        _layout_SECOND_label: "Andra",
        _action_toggleSidebar_label: "Växla sidopanel",
        _action_openSidebar_label: "Öppna sidopanel",
        widgetProperties: "Widgetegenskaper",
        widgetFunctions: "Widgetfunktioner",
        widgetName: "widgetens namn:",
        widgetProps: "widgetegenskaper:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
