/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kenar çubuğu",
        _layout_FIRST_label: "Birinci",
        _layout_SECOND_label: "Saniye",
        _action_toggleSidebar_label: "Yan çubuğu aç/kapat",
        _action_openSidebar_label: "Yan çubuğu aç",
        widgetProperties: "Araç özellikleri",
        widgetFunctions: "Araç işlevleri",
        widgetName: "araç adı:",
        widgetProps: "araç özellikleri:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
