/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Бічна панель",
        _layout_FIRST_label: "Перший",
        _layout_SECOND_label: "Секунда",
        _action_toggleSidebar_label: "Увімкнути бічну панель",
        _action_openSidebar_label: "Відкрити бічну панель",
        widgetProperties: "Властивості віджету",
        widgetFunctions: "Функції віджету",
        widgetName: "назва віджету:",
        widgetProps: "властивості віджету:"
      })
    }
  }
})
