/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Thanh bên",
        _layout_FIRST_label: "Đầu tiên",
        _layout_SECOND_label: "Giây",
        _action_toggleSidebar_label: "Bật/tắt thanh bên",
        _action_openSidebar_label: "Mở thanh bên",
        widgetProperties: "Thuộc tính tiện ích",
        widgetFunctions: "Chức năng tiện ích",
        widgetName: "tên tiện ích:",
        widgetProps: "thuộc tính tiện ích:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
