/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "侧边栏",
        _layout_FIRST_label: "首页",
        _layout_SECOND_label: "秒",
        _action_toggleSidebar_label: "切换侧边栏",
        _action_openSidebar_label: "打开侧边栏",
        widgetProperties: "微件属性",
        widgetFunctions: "微件功能",
        widgetName: "微件名称：",
        widgetProps: "微件属性：",
        noLayoutComponent: "没有布局组件 !",
        unknownError: "未知错误",
        unserializableError: "无序错误",
        online101: "在线 10.1."
      })
    }
  }
})
