/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "資訊看板",
        _layout_FIRST_label: "第一頁",
        _layout_SECOND_label: "秒",
        _action_toggleSidebar_label: "切換側軸",
        _action_openSidebar_label: "開啟側軸",
        widgetProperties: "Widget 屬性",
        widgetFunctions: "Widget 函數",
        widgetName: "widget 名稱:",
        widgetProps: "widget 屬性:",
        noLayoutComponent: "No layout component!",
        unknownError: "unknown error",
        unserializableError: "unserializable error",
        online101: "Online 10.1."
      })
    }
  }
})
