/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "مُوسَّع",
        collapsed: "مطوي",
        panel: "اللوحة الجانبية",
        overlay: "تراكب",
        resizable: "قابل لتغيير الحجم",
        defaultState: "الحالة الافتراضية",
        toggleBtn: "زر الطي",
        divider: "المقسم",
        leftPanel: "اللوحة اليسرى",
        topPanel: "اللوحة العلوية",
        rightPanel: "اللوحة اليمنى",
        bottomPanel: "اللوحة السفلية",
        size: "الحجم",
        dockSide: "جانب الإرساء",
        rounded: "مستدير",
        square: "مربع"
      })
    }
  }
})
