/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Prošireno",
        collapsed: "Sažeto",
        panel: "Bočna ploča",
        overlay: "Preklapanje",
        resizable: "Promjenjiva veličina",
        defaultState: "Zadano stanje",
        toggleBtn: "Gumb za sažimanje",
        divider: "Razdjeljivač",
        leftPanel: "Lijeva ploča",
        topPanel: "Gornja ploča",
        rightPanel: "Desna ploča",
        bottomPanel: "Donja ploča",
        size: "Veličina",
        dockSide: "Strana spoja",
        rounded: "Zaokruženo",
        square: "Kvadrat"
      })
    }
  }
})
