/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Επιτυχής ανάπτυξη",
        collapsed: "Επιτυχής σύμπτυξη",
        panel: "Πλαϊνός πίνακας",
        overlay: "Υπέρθεση",
        resizable: "Με δυνατότητα αλλαγής μεγέθους",
        defaultState: "Προεπιλεγμένη κατάσταση",
        toggleBtn: "Κουμπί σύμπτυξης",
        divider: "Διαχωριστικό",
        leftPanel: "Αριστερό πλαίσιο",
        topPanel: "Επάνω πλαίσιο",
        rightPanel: "Δεξί πλαίσιο",
        bottomPanel: "Κάτω πλαίσιο",
        size: "Μέγεθος",
        dockSide: "Μέγεθος βάσης αγκύρωσης",
        rounded: "Στρογγυλεμένο",
        square: "Τετράγωνο"
      })
    }
  }
})
