/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Laiendatud",
        collapsed: "Ahendatud",
        panel: "Külgpaneel",
        overlay: "Ülekate",
        resizable: "Muudetava suurusega",
        defaultState: "Vaikeolek",
        toggleBtn: "Ahenda nupp",
        divider: "Jagaja",
        leftPanel: "Vasakpaneel",
        topPanel: "Ülapaneel",
        rightPanel: "Parempaneel",
        bottomPanel: "Alapaneel",
        size: "Suurus",
        dockSide: "Doki külg",
        rounded: "Ümar",
        square: "Ruut"
      })
    }
  }
})
