/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Laajennettu",
        collapsed: "Kutistettu",
        panel: "Sivupaneeli",
        overlay: "Päällekkäisyys",
        resizable: "Koko muutettavissa",
        defaultState: "Oletustila",
        toggleBtn: "Tiivistä-painike",
        divider: "Jakaja",
        leftPanel: "Vasen paneeli",
        topPanel: "Yläpaneeli",
        rightPanel: "Oikea paneeli",
        bottomPanel: "Alapaneeli",
        size: "Koko",
        dockSide: "Kiinnitysreuna",
        rounded: "Pyöristetty",
        square: "Neliö"
      })
    }
  }
})
