/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "מורחב",
        collapsed: "מצומצם",
        panel: "לוח צדדי",
        overlay: "חפיפה",
        resizable: "ניתן לשינוי גודל",
        defaultState: "מדינת ברירת מחדל",
        toggleBtn: "לחצן כיווץ",
        divider: "מפריד",
        leftPanel: "לוח שמאלי",
        topPanel: "לוח עליון",
        rightPanel: "לוח ימני",
        bottomPanel: "לוח תחתון",
        size: "גודל",
        dockSide: "עגן צד",
        rounded: "מעוגל",
        square: "מרובע"
      })
    }
  }
})
