/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Dibentangkan",
        collapsed: "Ditutup",
        panel: "Panel sisi",
        overlay: "Overlay",
        resizable: "Dapat diubah ukurannya",
        defaultState: "Status default",
        toggleBtn: "Tombol tutup",
        divider: "Pemisah",
        leftPanel: "Panel kiri",
        topPanel: "Panel atas",
        rightPanel: "Panel kanan",
        bottomPanel: "Panel bawah",
        size: "Ukuran",
        dockSide: "Dok samping",
        rounded: "Bulat",
        square: "Kotak"
      })
    }
  }
})
