/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Espanso",
        collapsed: "Compresso",
        panel: "Riquadro laterale",
        overlay: "Sovrapposizione",
        resizable: "Ridimensionabile",
        defaultState: "Stato predefinito",
        toggleBtn: "Pulsante Comprimi",
        divider: "Divisore",
        leftPanel: "Panello sinistro",
        topPanel: "Pannello superiore",
        rightPanel: "Pannello destro",
        bottomPanel: "Pannello inferiore",
        size: "Dimensione",
        dockSide: "Lato del dock",
        rounded: "Arrotondato",
        square: "Quadrati"
      })
    }
  }
})
