/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Išskleistas",
        collapsed: "Suskleisti",
        panel: "Šoninis skydelis",
        overlay: "Perdanga",
        resizable: "Keičiamo dydžio",
        defaultState: "Numatytoji būsena",
        toggleBtn: "Sutraukimo mygtukas",
        divider: "Dalijimas",
        leftPanel: "Kairysis skydelis",
        topPanel: "Viršutinis skydelis",
        rightPanel: "Dešinysis skydelis",
        bottomPanel: "Apatinis skydelis",
        size: "Dydis",
        dockSide: "Šoninis Dock",
        rounded: "Apvalinta",
        square: "Kvadratas"
      })
    }
  }
})
