/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Izvērsts",
        collapsed: "Sakļauts",
        panel: "Sānu panelis",
        overlay: "Pārklājums",
        resizable: "Maināmi izmēri",
        defaultState: "Noklusējuma stāvoklis",
        toggleBtn: "Sakļaušanas poga",
        divider: "Atdalītājs",
        leftPanel: "Kreisais panelis",
        topPanel: "Augšējais panelis",
        rightPanel: "Labais panelis",
        bottomPanel: "Apakšējais panelis",
        size: "Izmērs",
        dockSide: "Dokošanas puse",
        rounded: "Apaļš",
        square: "Kvadrāts"
      })
    }
  }
})
