/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Uitgeklapt",
        collapsed: "Samengevouwen",
        panel: "Zijpaneel",
        overlay: "Overlay",
        resizable: "Grootte aanpasbaar",
        defaultState: "Standaardstaat",
        toggleBtn: "Knop inklappen",
        divider: "Verdeler",
        leftPanel: "Linkerpaneel",
        topPanel: "Bovenpaneel",
        rightPanel: "Rechterpaneel",
        bottomPanel: "Onderpaneel",
        size: "Grootte",
        dockSide: "Dockzijde",
        rounded: "Rond",
        square: "Vierkant"
      })
    }
  }
})
