/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Utvidet",
        collapsed: "Skjult",
        panel: "Sidepanel",
        overlay: "Overlegg",
        resizable: "Størrelse kan endres",
        defaultState: "Standardtilstand",
        toggleBtn: "Skjul knapp",
        divider: "Skillelinje",
        leftPanel: "Venstre panel",
        topPanel: "Øvre panel",
        rightPanel: "Høyre panel",
        bottomPanel: "Nedre panel",
        size: "Størrelse",
        dockSide: "Forankre side",
        rounded: "Avrundet",
        square: "Kvadrat"
      })
    }
  }
})
