/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Rozwinięte",
        collapsed: "Zwinięte",
        panel: "Panel boczny",
        overlay: "Nakładanie",
        resizable: "Możliwa zmiana rozmiaru",
        defaultState: "Stan domyślny",
        toggleBtn: "Przycisk Zwiń",
        divider: "Ogranicznik",
        leftPanel: "Lewy panel",
        topPanel: "Górny panel",
        rightPanel: "Prawy panel",
        bottomPanel: "Dolny panel",
        size: "Rozmiar",
        dockSide: "Strona dokowania",
        rounded: "Zaokrąglony",
        square: "Kwadrat"
      })
    }
  }
})
