/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Expandido",
        collapsed: "Recolhido",
        panel: "Painel lateral",
        overlay: "Sobreposição",
        resizable: "Redimensionável",
        defaultState: "Estado padrão",
        toggleBtn: "Botão recolher",
        divider: "Divisor",
        leftPanel: "Painel esquerdo",
        topPanel: "Painel superior",
        rightPanel: "Painel direito",
        bottomPanel: "Painel inferior",
        size: "Tamanho",
        dockSide: "Lateral",
        rounded: "Arredondado",
        square: "Equacionar"
      })
    }
  }
})
