/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Extins",
        collapsed: "Restrâns",
        panel: "Panou lateral",
        overlay: "Suprapunere",
        resizable: "Redimensionabil",
        defaultState: "Stare implicită",
        toggleBtn: "Butonul Restrângere",
        divider: "Divizor",
        leftPanel: "Panou stâng",
        topPanel: "Panou superior",
        rightPanel: "Panou drept",
        bottomPanel: "Panou inferior",
        size: "Dimensiune",
        dockSide: "Partea de andocare",
        rounded: "Rotunjită",
        square: "Pătrat"
      })
    }
  }
})
