/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Rozšírené",
        collapsed: "Sklapnuté",
        panel: "Bočný panel",
        overlay: "Prekrytie",
        resizable: "Možné zmeniť veľkosť",
        defaultState: "Predvolený stav",
        toggleBtn: "Tlačidlo zvinutia",
        divider: "Rozdeľovač",
        leftPanel: "Ľavý panel",
        topPanel: "Horný panel",
        rightPanel: "Pravý panel",
        bottomPanel: "Dolný panel",
        size: "Veľkosť",
        dockSide: "Strana ukotvenia",
        rounded: "Zaoblené",
        square: "Štvorec"
      })
    }
  }
})
