/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Prošireno",
        collapsed: "Skupljeno",
        panel: "Bočni panel",
        overlay: "Preklapanje",
        resizable: "Promenljive veličine",
        defaultState: "Podrazumevano stanje",
        toggleBtn: "Sklopi dugme",
        divider: "Delilac",
        leftPanel: "Leva tabla",
        topPanel: "Gornja tabla",
        rightPanel: "Desna tabla",
        bottomPanel: "Donja tabla",
        size: "Veličina",
        dockSide: "Strana za priključak",
        rounded: "Zaobljeno",
        square: "Kvadrat"
      })
    }
  }
})
