/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        expanded: "Đã mở rộng",
        collapsed: "Thu gọn",
        panel: "Bảng điều khiển bên",
        overlay: "Lớp chồng",
        resizable: "Có thể thay đổi kích thước",
        defaultState: "Trạng thái mặc định",
        toggleBtn: "Nút thu gọn",
        divider: "Bộ chia",
        leftPanel: "Bảng điều khiển bên trái",
        topPanel: "Bảng điều khiển trên",
        rightPanel: "Bảng điều khiển bên phải",
        bottomPanel: "Bảng điều khiển dưới",
        size: "Kích thước",
        dockSide: "Dock side",
        rounded: "Bo tròn",
        square: "Hình vuông"
      })
    }
  }
})
